spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codecrafters_db
    username: cc
    password: cc155
  jpa.hibernate.ddl-auto: create

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    generic-properties:
      properties:
        historyTimeToLive: 5
